# Generated by Django 5.2.14 on 2026-07-13 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0016_purchaseorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DscTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='Can be auto-populated from Director Master or User Master', max_length=255, verbose_name='Name')),
                ('pan', models.CharField(blank=True, help_text='Can be auto-populated from Director Master', max_length=20, null=True, verbose_name='PAN')),
                ('father_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="Father's Name")),
                ('from_date', models.DateField(blank=True, help_text='Can be auto-populated from Director Master', null=True, verbose_name='From Date')),
                ('to_date', models.DateField(blank=True, help_text='Can be auto-populated from Director Master', null=True, verbose_name='To Date')),
                ('dsc_registered_on_it', models.BooleanField(default=False, verbose_name='Whether DSC registered on IT')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('director', models.ForeignKey(blank=True, help_text='Select a Director to auto-populate Name, PAN, From/To Date', null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.director', verbose_name='Director')),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user_master', models.ForeignKey(blank=True, help_text='Select a User to auto-populate Name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.usermaster', verbose_name='User Master')),
            ],
            options={
                'verbose_name': 'DSC Tracker',
                'verbose_name_plural': 'DSC Trackers',
                'db_table': 'dsc_tracker',
            },
        ),
    ]
