# Generated by Django 5.2.14 on 2026-07-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsctracker',
            name='director',
        ),
        migrations.RemoveField(
            model_name='dsctracker',
            name='user_master',
        ),
        migrations.AlterField(
            model_name='dsctracker',
            name='from_date',
            field=models.DateField(blank=True, null=True, verbose_name='From Date'),
        ),
        migrations.AlterField(
            model_name='dsctracker',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='dsctracker',
            name='pan',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PAN'),
        ),
        migrations.AlterField(
            model_name='dsctracker',
            name='to_date',
            field=models.DateField(blank=True, null=True, verbose_name='To Date'),
        ),
    ]
