# Generated by Django 5.2.14 on 2026-07-13 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0016_purchaseorder'),
        ('registration', '0002_remove_dsctracker_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsctracker',
            name='director',
            field=models.ForeignKey(blank=True, help_text='Select a Director to auto-populate Name, PAN', null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.director', verbose_name='Director'),
        ),
        migrations.AlterField(
            model_name='dsctracker',
            name='from_date',
            field=models.DateField(blank=True, help_text='Auto-populated from selected Director', null=True, verbose_name='From Date'),
        ),
        migrations.AlterField(
            model_name='dsctracker',
            name='name',
            field=models.CharField(blank=True, help_text="Auto-populated from selected Director's name", max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='dsctracker',
            name='pan',
            field=models.CharField(blank=True, help_text="Auto-populated from selected Director's PAN", max_length=20, null=True, verbose_name='PAN'),
        ),
        migrations.AlterField(
            model_name='dsctracker',
            name='to_date',
            field=models.DateField(blank=True, help_text='Auto-populated from selected Director', null=True, verbose_name='To Date'),
        ),
    ]
