# Generated by Django 5.2.14 on 2026-07-13 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0016_purchaseorder'),
        ('registration', '0003_dsctracker_director_alter_dsctracker_from_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerOfAttorneyTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('entity_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Entity')),
                ('poa_holder_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of POA Holder')),
                ('pan', models.CharField(blank=True, max_length=20, null=True, verbose_name='PAN')),
                ('from_date', models.DateField(blank=True, null=True, verbose_name='From Date')),
                ('to_date', models.DateField(blank=True, null=True, verbose_name='To Date')),
                ('poa_repository', models.FileField(blank=True, null=True, upload_to='poa_repository/', verbose_name='POA Repository')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('forum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.forum', verbose_name='Forum')),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_last_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Power Of Attorney Tracker',
                'verbose_name_plural': 'Power Of Attorney Trackers',
                'db_table': 'power_of_attorney_tracker',
            },
        ),
    ]
