# Generated by Django 5.2.14 on 2026-07-13 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0016_purchaseorder'),
        ('registration', '0004_powerofattorneytracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsctracker',
            name='director',
        ),
        migrations.AlterField(
            model_name='dsctracker',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.director', verbose_name='Name'),
        ),
    ]
