# Generated by Django 5.2.14 on 2026-07-13 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0016_purchaseorder'),
        ('registration', '0005_remove_dsctracker_director_alter_dsctracker_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpinionManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('name_of_counsel_firm', models.CharField(max_length=255, verbose_name='Name of Counsel/ Firm')),
                ('purpose', models.CharField(blank=True, max_length=500, null=True, verbose_name='Purpose')),
                ('date_of_opinion', models.DateField(blank=True, null=True, verbose_name='Date of Opinion')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='registration/opinion_management/', verbose_name='Attachment (Download)')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.legalentity', verbose_name='Name of Entity')),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('team_member_involved', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.usermaster', verbose_name='Team member involved')),
            ],
            options={
                'verbose_name': 'Opinion Management',
                'verbose_name_plural': 'Opinion Management',
                'db_table': 'opinion_management',
            },
        ),
    ]
