# Generated by Django 5.2.14 on 2026-07-14 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0016_purchaseorder'),
        ('registration', '0008_cleanup_poa_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationReportManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('name_of_firm_counsel', models.CharField(max_length=255, verbose_name='Name of the Firm/ Counsel')),
                ('date_of_report', models.DateField(blank=True, null=True, verbose_name='Date of Report')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='registration/valuation_report/', verbose_name='Attachment (Download)')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.legalentity', verbose_name='Name of entity')),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('purpose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.law', verbose_name='Purpose')),
                ('team_member_involved', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.usermaster', verbose_name='Team Member Involved')),
            ],
            options={
                'verbose_name': 'Valuation Report Management',
                'verbose_name_plural': 'Valuation Report Management',
                'db_table': 'valuation_report_management',
            },
        ),
    ]
