# Generated by Django 5.2.14 on 2026-07-14 10:27

import registration.models.opinion_management
import registration.models.poa_tracker
import registration.models.valuation_report_management
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_valuationreportmanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinionmanagement',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=registration.models.opinion_management.opinion_management_upload_to, verbose_name='Attachment (Download)'),
        ),
        migrations.AlterField(
            model_name='poatracker',
            name='poa_repository',
            field=models.FileField(blank=True, null=True, upload_to=registration.models.poa_tracker.poa_repository_upload_to, verbose_name='POA Repository'),
        ),
        migrations.AlterField(
            model_name='valuationreportmanagement',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=registration.models.valuation_report_management.valuation_report_upload_to, verbose_name='Attachment (Download)'),
        ),
    ]
