# Generated by Django 5.2.14 on 2026-07-15 08:15

import django.db.models.deletion
import registration.models.form_management
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0016_purchaseorder'),
        ('registration', '0010_alter_opinionmanagement_attachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('filing_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Filing Type')),
                ('acknowledgement_upload', models.FileField(blank=True, null=True, upload_to=registration.models.form_management.form_management_upload_to, verbose_name='Acknowledgement Upload')),
                ('form_upload', models.FileField(blank=True, null=True, upload_to=registration.models.form_management.form_management_upload_to, verbose_name='Form Upload')),
                ('statutory_timelines', models.DateField(blank=True, null=True, verbose_name='Statutory Timelines')),
                ('internal_timelines', models.DateField(blank=True, null=True, verbose_name='Internal Timelines')),
                ('actual_completion_date', models.DateField(blank=True, null=True, verbose_name='Actual Completion Date')),
                ('status_by_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status by User')),
                ('assessment_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.assessmentyear', verbose_name='Assessment Year')),
                ('compliance_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.compliance', verbose_name='Compliance Name')),
                ('compliance_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.lawsection', verbose_name='Compliance Section')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('financial_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.financialyear', verbose_name='Financial Year')),
                ('form_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.formmaster', verbose_name='Form No.')),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('pan', models.ForeignKey(blank=True, help_text='Select PAN from Legal Entity Master', null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.legalentity', verbose_name='PAN')),
            ],
            options={
                'verbose_name': 'Form Management',
                'verbose_name_plural': 'Form Management',
                'db_table': 'form_management',
            },
        ),
    ]
