# Generated by Django 5.2.14 on 2026-07-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_formmanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmanagement',
            name='form_description',
            field=models.CharField(blank=True, help_text='Auto-populated from Form Master based on selected Form No.', max_length=255, null=True, verbose_name='Form No. Description'),
        ),
    ]
