# Generated by Django 5.2.14 on 2026-07-16 06:12

import django.db.models.deletion
import registration.models.compliance_management
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0016_purchaseorder'),
        ('registration', '0012_formmanagement_form_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('legal_entity', models.CharField(blank=True, help_text='Auto-filled from Legal Entity Master based on selected PAN', max_length=255, null=True, verbose_name='Legal Entity')),
                ('frequency', models.CharField(blank=True, help_text='Auto-filled from Compliance Master based on selected Compliance Name', max_length=100, null=True, verbose_name='Frequency')),
                ('statutory_timelines', models.DateField(blank=True, null=True, verbose_name='Statutory Timelines')),
                ('internal_timelines', models.DateField(blank=True, null=True, verbose_name='Internal Timelines')),
                ('actual_completion_date', models.DateField(blank=True, null=True, verbose_name='Actual Completion Date')),
                ('status_by_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status by User')),
                ('document_link', models.FileField(blank=True, help_text='Captures documents uploaded by user in Return/Form Management', null=True, upload_to=registration.models.compliance_management.compliance_management_upload_to, verbose_name='Document Link')),
                ('status_by_workspace_admin', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status by Workspace Admin')),
                ('status_from_income_tax_website', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status from Income Tax Website')),
                ('compliance_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.compliance', verbose_name='Compliance Name')),
                ('compliance_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.lawsection', verbose_name='Compliance Section')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('law_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.law', verbose_name='Law Name')),
                ('pan', models.ForeignKey(blank=True, help_text='Select PAN from Legal Entity Master', null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.legalentity', verbose_name='PAN')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.period', verbose_name='Period')),
                ('user_involved', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.usermaster', verbose_name='User Involved')),
                ('vertical', models.ForeignKey(blank=True, help_text='Auto-filled based on selected PAN', null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.vertical', verbose_name='Vertical')),
            ],
            options={
                'verbose_name': 'Compliance Management',
                'verbose_name_plural': 'Compliance Management',
                'db_table': 'compliance_management',
            },
        ),
    ]
