# Generated by Django 5.2.14 on 2026-07-16 06:48

import django.db.models.deletion
import django.db.models.deletion
from django.db import migrations, models


def clear_frequency_values(apps, schema_editor):
    """Clear existing CharField frequency values before converting to FK."""
    ComplianceManagement = apps.get_model("registration", "ComplianceManagement")
    ComplianceManagement.objects.exclude(frequency="").exclude(frequency__isnull=True).update(frequency=None)


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0016_purchaseorder'),
        ('registration', '0013_compliancemanagement'),
    ]

    operations = [
        migrations.RunPython(clear_frequency_values, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='compliancemanagement',
            name='frequency',
            field=models.ForeignKey(blank=True, help_text='Dropdown from Compliance Name Master', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_management_frequency', to='masters.compliance', verbose_name='Frequency'),
        ),
    ]
