# Generated by Django 5.2.14 on 2026-07-16 07:03

import django.db.models.deletion
import registration.models.itr_status_management
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0016_purchaseorder'),
        ('registration', '0014_alter_compliancemanagement_frequency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItrStatusManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('legal_entity', models.CharField(blank=True, help_text='Auto-filled from Legal Entity Master based on selected PAN', max_length=255, null=True, verbose_name='Legal Entity')),
                ('filing_type', models.CharField(blank=True, help_text='Manual entry (e.g., Original, Revised)', max_length=100, null=True, verbose_name='Filing Type')),
                ('acknowledgement_upload', models.FileField(blank=True, null=True, upload_to=registration.models.itr_status_management.itr_status_management_upload_to, verbose_name='Acknowledgement Upload')),
                ('itr_form_upload', models.FileField(blank=True, null=True, upload_to=registration.models.itr_status_management.itr_status_management_upload_to, verbose_name='ITR Form Upload')),
                ('statutory_timelines', models.DateField(blank=True, null=True, verbose_name='Statutory Timelines')),
                ('internal_timelines', models.DateField(blank=True, null=True, verbose_name='Internal Timelines')),
                ('actual_completion_date', models.DateField(blank=True, null=True, verbose_name='Actual Completion Date')),
                ('status_by_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status by User')),
                ('assessment_year', models.ForeignKey(blank=True, help_text='Dropdown from Period Master', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itr_status_assessment_year', to='masters.period', verbose_name='Assessment Year')),
                ('compliance_section', models.ForeignKey(blank=True, help_text='Dropdown from Law Section Master', null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.lawsection', verbose_name='Compliance Section')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('financial_year', models.ForeignKey(blank=True, help_text='Dropdown from Period Master', null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.period', verbose_name='Financial Year')),
                ('itr_form', models.ForeignKey(blank=True, help_text='Select ITR form from Form Master', null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.formmaster', verbose_name='ITR Form')),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('pan', models.ForeignKey(blank=True, help_text='Dropdown from Legal Entity Master', null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.legalentity', verbose_name='PAN')),
            ],
            options={
                'verbose_name': 'ITR Status Management',
                'verbose_name_plural': 'ITR Status Management',
                'db_table': 'itr_status_management',
            },
        ),
    ]
