# Generated by Django 5.2.14 on 2026-07-16 10:22

import django.db.models.deletion
import registration.models.document_vault
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0016_purchaseorder'),
        ('registration', '0015_itrstatusmanagement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('pan', models.CharField(blank=True, help_text='Auto-filled from Legal Entity Master based on selected Legal Entity', max_length=50, null=True, verbose_name='PAN')),
                ('fy_ay', models.CharField(blank=True, help_text='Financial Year / Assessment Year', max_length=50, null=True, verbose_name='FY / AY')),
                ('document_name_download', models.CharField(blank=True, help_text='Auto-captured from downloaded file', max_length=255, null=True, verbose_name='Name of the Document - as per download')),
                ('document_download_date', models.DateField(blank=True, null=True, verbose_name='Document Download Date')),
                ('rename_date', models.DateField(blank=True, help_text='Auto-populated when document is renamed', null=True, verbose_name='Rename Date')),
                ('document_attachment', models.FileField(blank=True, null=True, upload_to=registration.models.document_vault.document_vault_upload_to, verbose_name='Document Attachment')),
                ('din', models.CharField(blank=True, help_text='Document Identification Number', max_length=100, null=True, verbose_name='DIN')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('document_name_renamed', models.ForeignKey(blank=True, help_text='Dropdown from Document Name Master', null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.documentmaster', verbose_name='Name of the Document - renamed')),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('legal_entity', models.ForeignKey(blank=True, help_text='Dropdown from Legal Entity Master', null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.legalentity', verbose_name='Legal Entity')),
                ('renamed_by', models.ForeignKey(blank=True, help_text='Dropdown from User Master', null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.usermaster', verbose_name='Renamed By')),
            ],
            options={
                'verbose_name': 'Document Vault',
                'verbose_name_plural': 'Document Vault',
                'db_table': 'document_vault',
            },
        ),
    ]
