# Generated by Django 6.0.7 on 2026-07-17 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0016_purchaseorder'),
        ('registration', '0017_opinionmanagement_multiselect_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itrstatusmanagement',
            name='assessment_year',
            field=models.ForeignKey(blank=True, help_text='Dropdown from Assessment Year Master', null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.assessmentyear', verbose_name='Assessment Year'),
        ),
        migrations.AlterField(
            model_name='itrstatusmanagement',
            name='filing_type',
            field=models.CharField(blank=True, help_text='Dropdown: Original, Revised, Updated, Modified', max_length=100, null=True, verbose_name='Filing Type'),
        ),
        migrations.AlterField(
            model_name='itrstatusmanagement',
            name='financial_year',
            field=models.ForeignKey(blank=True, help_text='Dropdown from Financial Year Master', null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.financialyear', verbose_name='Financial Year'),
        ),
        migrations.AlterField(
            model_name='itrstatusmanagement',
            name='itr_form',
            field=models.CharField(blank=True, help_text='Dropdown: ITR 5, ITR 6, ITR 7', max_length=100, null=True, verbose_name='ITR Form'),
        ),
    ]
