# Generated by Django 6.0.7 on 2026-07-17 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0016_purchaseorder'),
        ('registration', '0020_valuationreport_multiselect_team_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('task_name', models.CharField(blank=True, help_text='Based on Email to tag', max_length=255, null=True, verbose_name='Task Name')),
                ('priority', models.CharField(blank=True, help_text='Low / Medium / High', max_length=20, null=True, verbose_name='Priority')),
                ('status', models.CharField(blank=True, help_text='Open / WIP / Close', max_length=20, null=True, verbose_name='Status')),
                ('statutory_date', models.DateField(blank=True, null=True, verbose_name='Statutory Date')),
                ('internal_date', models.DateField(blank=True, null=True, verbose_name='Internal Date')),
                ('reminder_date', models.DateField(blank=True, null=True, verbose_name='Reminder Date')),
                ('assign_to', models.ForeignKey(blank=True, help_text='From User Master', null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.usermaster', verbose_name='Assign To')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('fy', models.ForeignKey(blank=True, help_text='From Period Master', null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.period', verbose_name='FY')),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('legal_entity', models.ForeignKey(blank=True, help_text='From Legal Entity Master', null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.legalentity', verbose_name='Legal Entity')),
            ],
            options={
                'verbose_name': 'Task Tracker',
                'verbose_name_plural': 'Task Tracker',
                'db_table': 'task_tracker',
            },
        ),
    ]
