# Generated by Django 5.2.14 on 2026-07-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_tasktracker_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmanagement',
            name='legal_entity',
            field=models.CharField(blank=True, help_text='Auto-filled from Legal Entity Master based on selected PAN', max_length=255, null=True, verbose_name='Legal Entity'),
        ),
    ]
