# Generated by Django 5.2.14 on 2026-07-18 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0016_purchaseorder'),
        ('registration', '0022_formmanagement_legal_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktracker',
            name='legal_entity_code',
            field=models.CharField(blank=True, help_text='Auto-filled from Legal Entity Master based on selected Legal Entity Name', max_length=50, null=True, verbose_name='Legal Entity Code'),
        ),
        migrations.AlterField(
            model_name='tasktracker',
            name='legal_entity',
            field=models.ForeignKey(blank=True, help_text='From Legal Entity Master', null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.legalentity', verbose_name='Legal Entity Name'),
        ),
    ]
