# Generated by Django 6.0.7 on 2026-07-20 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0016_purchaseorder'),
        ('registration', '0023_tasktracker_legal_entity_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktracker',
            name='fy',
            field=models.ForeignKey(blank=True, help_text='From Period Master', null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.financialyear', verbose_name='FY'),
        ),
    ]
