# Generated by Django 6.0.7 on 2026-07-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_alter_tasktracker_fy'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsctracker',
            name='initial_reminder_sent',
            field=models.BooleanField(default=False, help_text='Whether the first expiry reminder email was sent', verbose_name='Initial 30-day reminder sent'),
        ),
        migrations.AddField(
            model_name='dsctracker',
            name='last_reminder_sent',
            field=models.DateField(blank=True, help_text='Date of the last weekly reminder sent', null=True, verbose_name='Last Reminder Sent'),
        ),
        migrations.AddField(
            model_name='dsctracker',
            name='new_dsc_prepared',
            field=models.BooleanField(blank=True, help_text='Whether a new DSC has been prepared (Yes/No/Not Asked)', null=True, verbose_name='New DSC Prepared?'),
        ),
        migrations.AddField(
            model_name='dsctracker',
            name='new_dsc_prepared_at',
            field=models.DateTimeField(blank=True, help_text='When the user responded about new DSC preparation', null=True, verbose_name='New DSC Response Date'),
        ),
    ]
