# Generated by Django 6.0.5 on 2026-06-05 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemittanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('request_id', models.CharField(max_length=100)),
                ('vendor_code', models.CharField(max_length=100)),
                ('vendor_name', models.CharField(max_length=255)),
                ('gross_amount_fc', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tds_amount_fc', models.DecimalField(decimal_places=2, max_digits=18)),
                ('gross_amount_inr', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tds_amount_inr', models.DecimalField(decimal_places=2, max_digits=18)),
                ('net_amount_inr', models.DecimalField(decimal_places=2, max_digits=18)),
                ('sap_document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_number', models.CharField(max_length=100)),
                ('form_145_ack_number', models.CharField(blank=True, max_length=100, null=True)),
                ('form_146_ack_number', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('form_145_attachment', models.FileField(blank=True, null=True, upload_to='remittance/form145/')),
                ('form_146_attachment', models.FileField(blank=True, null=True, upload_to='remittance/form146/')),
                ('trc_attachment', models.FileField(blank=True, null=True, upload_to='remittance/trc/')),
                ('no_pe_attachment', models.FileField(blank=True, null=True, upload_to='remittance/no_pe/')),
                ('form_10f_attachment', models.FileField(blank=True, null=True, upload_to='remittance/10f/')),
                ('invoice_attachment', models.FileField(blank=True, null=True, upload_to='remittance/invoice/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_last_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'remittance_report',
            },
        ),
    ]
