# Generated by Django 5.2.14 on 2026-06-10 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('tax_requests', '0004_remove_bankdetailstage_account_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remittancereport',
            name='tds_opinion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remittance_report', to='tax_requests.tdsopinion'),
        ),
        migrations.AlterField(
            model_name='remittancereport',
            name='form_10f_attachment',
            field=models.FileField(blank=True, null=True, upload_to='remittance/10f/', verbose_name='Form 10F'),
        ),
        migrations.AlterField(
            model_name='remittancereport',
            name='form_145_ack_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Form 145 Ackn. Number'),
        ),
        migrations.AlterField(
            model_name='remittancereport',
            name='form_145_attachment',
            field=models.FileField(blank=True, null=True, upload_to='remittance/form145/', verbose_name='Form 145 Attachment'),
        ),
        migrations.AlterField(
            model_name='remittancereport',
            name='form_146_ack_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Form 146 Ackn. Number'),
        ),
        migrations.AlterField(
            model_name='remittancereport',
            name='form_146_attachment',
            field=models.FileField(blank=True, null=True, upload_to='remittance/form146/', verbose_name='Form 146 Attachment'),
        ),
        migrations.AlterField(
            model_name='remittancereport',
            name='gross_amount_inr',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Gross Amt-INR'),
        ),
        migrations.AlterField(
            model_name='remittancereport',
            name='invoice_attachment',
            field=models.FileField(blank=True, null=True, upload_to='remittance/invoice/', verbose_name='Invoice'),
        ),
        migrations.AlterField(
            model_name='remittancereport',
            name='invoice_number',
            field=models.CharField(max_length=100, verbose_name='Invoice Number'),
        ),
        migrations.AlterField(
            model_name='remittancereport',
            name='net_amount_inr',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Net Amount-INR'),
        ),
        migrations.AlterField(
            model_name='remittancereport',
            name='no_pe_attachment',
            field=models.FileField(blank=True, null=True, upload_to='remittance/no_pe/', verbose_name='NO PE Attachment'),
        ),
        migrations.AlterField(
            model_name='remittancereport',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Payment Date'),
        ),
        migrations.AlterField(
            model_name='remittancereport',
            name='payment_document_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment Document Number'),
        ),
        migrations.AlterField(
            model_name='remittancereport',
            name='sap_document_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SAP Document Number'),
        ),
        migrations.AlterField(
            model_name='remittancereport',
            name='tds_amount_inr',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='TDS Amt-INR'),
        ),
        migrations.AlterField(
            model_name='remittancereport',
            name='trc_attachment',
            field=models.FileField(blank=True, null=True, upload_to='remittance/trc/', verbose_name='TRC Attachment'),
        ),
    ]
