# Generated by Django 5.2.14 on 2026-07-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remittancereport_tds_opinion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remittancereport',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
