# Generated by Django 5.2.14 on 2026-07-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remittancereport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='remittancereport',
            name='revert',
            field=models.BooleanField(default=False, verbose_name='Reverted'),
        ),
    ]
