# Generated by Django 5.2.14 on 2026-07-12 03:52

from django.db import migrations


def backfill_revert(apps, schema_editor):
    RemittanceReport = apps.get_model("reports", "RemittanceReport")
    RemittanceReport.objects.filter(status="Returned").update(revert=True)


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remittancereport_revert'),
    ]

    operations = [
        migrations.RunPython(backfill_revert, migrations.RunPython.noop),
    ]
