export const MASTER_FIELDS = [
  { key: "remarks", label: "Remarks, if any", type: "textarea" },
  {
    key: "company",
    label: "Company",
    type: "fk",
    api: "masters/legalentity",
    labelFields: ["sap_code", "entity_name"],
    dropdownParams: { fields: "sap_code,entity_name", search_fields: "sap_code,entity_name" },
    required: true,
  },
  // { key: "vendor", label: "Vendor", type: "text" },
  {
    key: "vendor",
    label: "Vendor",
    type: "supplier_search",
    api: "masters/supplier",
    labelFields: ["vendor_name", "vendor_code"],
    dropdownParams: {
      search_fields: "vendor_name,vendor_code",
    },
    required: true,
  },
  { key: "pan_number", label: "PAN Number", type: "text" },
  { key: "tin_number", label: "TIN Number", type: "text" },
  { key: "po_npo", label: "PO / NPO", type: "checkbox", required: true },
  {
    key: "po_number",
    label: "PO Number",
    type: "fk",
    api: "masters/purchaseorder",
    labelFields: ["purchase_order_number"],
  },
  { key: "grossing_up", label: "Grossing up", type: "checkbox", required: true },
  { key: "currency", label: "Currency", type: "fk", api: "masters/currency", labelFields: ["currency"], required: true },
  { key: "particular", label: "Particular", type: "fk", api: "masters/particular", labelFields: ["particular_name"], required: true },
  { key: "invoice_number", label: "Invoice Number", type: "text", required: true },
  { key: "opinion_invoice_amount", label: "Opinion/Invoice Amount", type: "number", required: true },
  { key: "invoice_date", label: "Invoice Date", type: "date", required: true },
  { key: "invoice_file", label: "Invoice File", type: "file", required: true },
  { key: "form_10f_file", label: "Electronically filed form 10F", type: "file" },
  { key: "form_10f_valid_upto", label: "Valid Upto", type: "date" },
  { key: "trc_file", label: "Tax Residency Certificate (TRC)", type: "file" },
  { key: "trc_valid_upto", label: "Valid Upto", type: "date" },
  { key: "contract_agreement_copy", label: "Contract/ Agreement Copy", type: "file" },
  { key: "agreement_valid_upto", label: "Valid Upto", type: "date" },
  { key: "pan_file", label: "PAN", type: "file" },
  { key: "pan_valid_upto", label: "Valid Upto", type: "date" },
  { key: "no_pe_declaration_file", label: "No Permanent (NO PE) Establishment Declaration", type: "file" },
  { key: "no_pe_valid_upto", label: "Valid Upto", type: "date" },
  { key: "proof_of_reimbursement_file", label: "Proof of reimbursement claims", type: "file" },
  { key: "reimbursement_valid_upto", label: "Valid Upto", type: "date" },
];

export const STAGE_FIELD_CONFIG = {
  tds_opinion_stage: [
    { key: "opinion_remarks", label: "Remarks, if any", type: "textarea" },
    {
      key: "country",
      label: "Country",
      type: "fk",
      api: "masters/country",
      labelFields: ["country_name"],
    },
    {
      key: "vendor_status",
      label: "Status of Vendor",
      type: "fk",
      api: "masters/vendorstatus",
      labelFields: ["status_name"],
    },
    { key: "has_trc", label: "Tax Residency Certificate (TRC)", type: "checkbox" },
    { key: "has_no_pe", label: "No PE Declaration", type: "checkbox" },
    { key: "has_e_form_10f", label: "E form 10F", type: "checkbox" },
    {
      key: "it_or_dtaa",
      label: "As per IT or DTAA",
      type: "select",
      options: ["IT", "DTAA"],
    },
    { key: "grossing_up_applicable", label: "Grossing up or not", type: "checkbox" },
    {
      key: "nature_of_service",
      label: "Nature of Service",
      type: "fk",
      api: "masters/natureofservice",
      labelFields: ["service_description"],
    },
    {
      key: "currency",
      label: "Currency",
      type: "fk",
      api: "masters/currency",
      labelFields: ["currency"],
    },
    { key: "invoice_value_fc", label: "Invoice Value (FC)", type: "number" },
    { key: "taxable_in_india", label: "Whether Taxable in INDIA", type: "checkbox" },
    { key: "assesseable_value_fc", label: "Assesseable Value (FC)", type: "number" },
    { key: "exchange_rate_date", label: "Date of Exchange Rate", type: "date" },
    { key: "exchange_rate", label: "Exchange Rate", type: "number" },
    { key: "invoice_value_inr", label: "Invoice Value (INR)", type: "number", disabled: true },
    { key: "assesseable_value_inr", label: "Assesseable Value (INR)", type: "number", disabled: true },
    { key: "tds_section", label: "TDS Section", type: "fk", api: "masters/TDSSection", labelFields: ["TDS_section"] },
    {
      key: "tax_rate",
      label: "TDS Rate (%)",
      type: "tds_rate",
    },
    {
      key: "ldc_certificate",
      label: "LDC Certificate",
      type: "fk",
      api: "masters/LDCCertificate",
      labelFields: ["certificate_number"],
    },
    {
      key: "form_146_type",
      label: "Form 146 - Type",
      type: "fk",
      api: "masters/type15cb",
      labelFields: ["type_15cb"],
      note: "Note: This value can be changed in Bank Detail section",
    },
    { key: "tds_amount_fc", label: "TDS Amount (FC)", type: "number", disabled: true },
    { key: "tds_amount_inr", label: "TDS Amount (INR)", type: "number", disabled: true },
    { key: "net_payable_fc", label: "Net Payable (FC)", type: "number", disabled: true },
    { key: "net_payable_inr", label: "Net Payable (INR)", type: "number", disabled: true },
    { key: "income_amount", label: "Amount of income", type: "number" },
    { key: "external_document", label: "External Document", type: "file", note: ".pdf/.jpg/.jpeg/.png | Upto 10 MB." },
  ],
  invoice_posting: [
    { key: "posting_remarks", label: "Remarks, if any", type: "textarea" },
    { key: "document_number", label: "Document Number", type: "text", required: true },
    { key: "invoice_posting_date", label: "Invoice Posting Date", type: "date", required: true },
    { key: "description", label: "Description", type: "textarea", required: true },
  ],
  bank_detail: [
    { key: "bank_remarks", label: "Remarks, if any", type: "textarea" },
    {
      key: "bank_ifsc_code",
      label: "Bank IFSC Code",
      type: "fk",
      api: "masters/bank",
      labelFields: ["ifsc_code"],
      required: true,
    },
    { key: "bank_name", label: "Name of Bank", type: "text", disabled: true, },
    { key: "branch_name", label: "Branch of the Bank", type: "text", disabled: true, },
    { key: "bsr_code", label: "BSR Code", type: "text", disabled: true, },
    { key: "proposed_remittance_date", label: "Proposed date of remittance", type: "date", required: true },
    {
      key: "rbi_purpose_code",
      label: "RBI Purpose Code",
      type: "fk",
      api: "masters/rbipurposecode",
      labelFields: ["rbi_purpose_code"],
      required: true,
    },
    {
      key: "rbi_sub_code",
      label: "RBI Sub Code",
      type: "fk",
      api: "masters/rbipurposesubcode",
      labelFields: ["sub_code"],
      required: true,
    },
    {
      key: "form_146_type",
      label: "Form 146 - Type",
      type: "fk",
      api: "masters/Type15CB",
      labelFields: ["type_15cb"],
      required: true,
    },
    {
      key: "external_ca",
      label: "External CA",
      type: "fk",
      api: "masters/externalca",
      labelFields: ["firm_name"],
    },
    { key: "multiple_15ca_cb", label: "Multiple 15CA/CB", type: "checkbox", required: true },
    { key: "generate_single_15ca_cb", label: "Generate single 15CA/CB", type: "checkbox", required: true },
    { key: "itdrein", label: "ITDREIN", type: "text" },
  ],
  form_146: [
    { key: "remarks", label: "Remarks, if any", type: "textarea" },
    {
      key: "download_form_146",
      label: "Download Form 146",
      type: "button",
      action: "download_form_146",
    },

    {
      key: "download_form_146_comparison",
      label: "Download Form 146 Comparison",
      type: "button",
      action: "download_form_146_comparison",
      required: true 
    },
    { key: "form_146_attachment", label: "Form 146", type: "file", required: true },
    { key: "comparison_status", label: "Form 146 Comparison Status", type: "status", required: true  },
    { key: "ack_number", label: "Acknowledgement Number", type: "text", required: true },
    { key: "ack_date", label: "Acknowledgement Date", type: "date", required: true },
    { key: "udin", label: "UDIN", type: "text" },
    {
      key: "document_number",
      label: "Document Number",
      type: "text",
      disabled: true,
    },

    {
      key: "invoice_posting_date",
      label: "Invoice Posting Date",
      type: "date",
      disabled: true,
    },

    {
      key: "invoice_copy",
      label: "Invoice Copy",
      type: "file_link",
    },

    {
      key: "form_10f_file",
      label: "Electronically filed Form 10F",
      type: "file_link",
    },

    {
      key: "trc_file",
      label: "Tax Residency Certificate (TRC)",
      type: "file_link",
    },

    {
      key: "no_pe_declaration_file",
      label: "No PE Declaration",
      type: "file_link",
    },

  ],
  form_145: [
    { key: "remarks", label: "Remarks, if any", type: "textarea" },
    { key: "ack_number", label: "Acknowledgement Number", type: "text", required: true },
    { key: "posting_date", label: "Posting Date", type: "date", required: true },
    { key: "bot_status", label: "Bot Status", type: "text", required: true },
    { key: "form_145_file", label: "Form 145 file", type: "file", required: true },
  ],
  payment_detail: [
    { key: "remarks", label: "Remarks, if any", type: "textarea" },
    { key: "sap_document_number", label: "SAP Document Number", type: "text" },
    { key: "posting_date", label: "Posting Date", type: "date", required: true },
    { key: "payment_bank_documents", label: "Payment Bank Documents", type: "file", required: true },
    { key: "sap_username", label: "SAP Username", type: "text", disabled: true, required: true },
  ],
  close_request: [{ key: "closing_remarks", label: "Remarks, if any", type: "textarea", required: true }],
  approved: [{ key: "approval_remarks", label: "Approval Remarks", type: "textarea" }],
};

export const ALL_SECTION_FIELDS = {
  master: MASTER_FIELDS,
  ...STAGE_FIELD_CONFIG,
};
