export const MASTER_FIELDS = [
  { key: "remarks", label: "Remarks, if any", type: "textarea" },
  {
    key: "company",
    label: "Company",
    type: "fk",
    api: "masters/legalentity",
    labelFields: ["sap_code", "entity_name"],
    dropdownParams: { fields: "sap_code,entity_name", search_fields: "sap_code,entity_name" },
  },
  { key: "vendor", label: "Vendor", type: "text" },
  { key: "pan_number", label: "PAN Number", type: "text" },
  { key: "tin_number", label: "TIN Number", type: "text" },
  { key: "po_npo", label: "PO / NPO", type: "checkbox" },
  { key: "grossing_up", label: "Grossing up", type: "checkbox" },
  { key: "currency", label: "Currency", type: "fk", api: "masters/currency", labelFields: ["currency"] },
  { key: "particular", label: "Particular", type: "fk", api: "masters/particular", labelFields: ["particular_name"] },
  { key: "invoice_number", label: "Invoice Number", type: "text" },
  { key: "opinion_invoice_amount", label: "Opinion/Invoice Amount", type: "number" },
  { key: "invoice_date", label: "Invoice Date", type: "date" },
  { key: "invoice_file", label: "Invoice File", type: "file" },
  { key: "form_10f_file", label: "Electronically filed form 10F", type: "file" },
  { key: "form_10f_valid_upto", label: "Valid Upto", type: "date" },
  { key: "trc_file", label: "Tax Residency Certificate (TRC)", type: "file" },
  { key: "trc_valid_upto", label: "Valid Upto", type: "date" },
  { key: "contract_agreement_copy", label: "Contract/ Agreement Copy", type: "file" },
  { key: "agreement_valid_upto", label: "Valid Upto", type: "date" },
  { key: "pan_file", label: "PAN", type: "file" },
  { key: "pan_valid_upto", label: "Valid Upto", type: "date" },
  { key: "no_pe_declaration_file", label: "No Permanent (NO PE) Establishment Declaration", type: "file" },
  { key: "no_pe_valid_upto", label: "Valid Upto", type: "date" },
  { key: "proof_of_reimbursement_file", label: "Proof of reimbursement claims", type: "file" },
  { key: "reimbursement_valid_upto", label: "Valid Upto", type: "date" },
];

export const STAGE_FIELD_CONFIG = {
  tds_opinion_stage: [
    { key: "opinion_remarks", label: "Remarks, if any", type: "textarea" },
    { key: "country", label: "Country", type: "text" },
    { key: "vendor_status", label: "Status of Vendor", type: "text" },
    { key: "has_trc", label: "Tax Residency Certificate (TRC)", type: "checkbox" },
    { key: "has_no_pe", label: "No PE Declaration", type: "checkbox" },
    { key: "has_e_form_10f", label: "E form 10F", type: "checkbox" },
    { key: "it_or_dtaa", label: "As per IT or DTAA", type: "text" },
    { key: "grossing_up_applicable", label: "Grossing up or not", type: "checkbox" },
    { key: "nature_of_service", label: "Nature of Service", type: "text" },
    { key: "invoice_value_fc", label: "Invoice Value (FC)", type: "number" },
    { key: "taxable_in_india", label: "Whether Taxable in INDIA", type: "checkbox" },
    { key: "assesseable_value_fc", label: "Assesseable Value (FC)", type: "number" },
    { key: "exchange_rate_date", label: "Date of Exchange Rate", type: "date" },
    { key: "exchange_rate", label: "Exchange Rate", type: "number" },
    { key: "invoice_value_inr", label: "Invoice Value (INR)", type: "number" },
    { key: "assesseable_value_inr", label: "Assesseable Value (INR)", type: "number" },
    { key: "tds_section", label: "TDS Section", type: "text" },
    { key: "tax_rate", label: "TDS Rate (%)", type: "number" },
    { key: "ldc_certificate", label: "LDC Certificate", type: "text" },
    { key: "form_146_type", label: "Form 146 - Type", type: "text" },
    { key: "tds_amount_fc", label: "TDS Amount (FC)", type: "number" },
    { key: "tds_amount_inr", label: "TDS Amount (INR)", type: "number" },
    { key: "net_payable_fc", label: "Net Payable (FC)", type: "number" },
    { key: "net_payable_inr", label: "Net Payable (INR)", type: "number" },
    { key: "income_amount", label: "Amount of income", type: "number" },
    { key: "external_document", label: "External Document", type: "file" },
  ],
  invoice_posting: [
    { key: "posting_remarks", label: "Remarks, if any", type: "textarea" },
    { key: "document_number", label: "Document Number", type: "text" },
    { key: "invoice_posting_date", label: "Invoice Posting Date", type: "date" },
    { key: "description", label: "Description", type: "textarea" },
  ],
  bank_detail: [
    { key: "bank_remarks", label: "Remarks, if any", type: "textarea" },
    { key: "bank_ifsc_code", label: "Bank IFSC Code", type: "text" },
    { key: "bank_name", label: "Name of Bank", type: "text" },
    { key: "branch_name", label: "Branch of the Bank", type: "text" },
    { key: "bsr_code", label: "BSR Code", type: "text" },
    { key: "proposed_remittance_date", label: "Proposed date of remittance", type: "date" },
    { key: "rbi_purpose_code", label: "RBI Purpose Code", type: "text" },
    { key: "rbi_sub_code", label: "RBI Sub Code", type: "text" },
    { key: "form_146_type", label: "Form 146 - Type", type: "text" },
    { key: "external_ca", label: "External CA", type: "text" },
    { key: "multiple_15ca_cb", label: "Multiple 15CA/CB", type: "checkbox" },
    { key: "generate_single_15ca_cb", label: "Generate single 15CA/CB", type: "checkbox" },
    { key: "itdrein", label: "ITDREIN", type: "text" },
  ],
  form_146: [
    { key: "remarks", label: "Remarks, if any", type: "textarea" },
    { key: "form_146_attachment", label: "Form 146", type: "file" },
    { key: "comparison_status", label: "Form 146 Comparison Status", type: "text" },
    { key: "ack_number", label: "Acknowledgement Number", type: "text" },
    { key: "ack_date", label: "Acknowledgement Date", type: "date" },
    { key: "udin", label: "UDIN", type: "text" },
    { key: "sap_document_number", label: "SAP Document Number", type: "text" },
    { key: "invoice_posting_date", label: "Invoice Posting Date", type: "date" },
  ],
  form_145: [
    { key: "remarks", label: "Remarks, if any", type: "textarea" },
    { key: "ack_number", label: "Acknowledgement Number", type: "text" },
    { key: "posting_date", label: "Posting Date", type: "date" },
    { key: "bot_status", label: "Bot Status", type: "text" },
    { key: "form_ca_file", label: "Form CA file", type: "file" },
  ],
  payment_detail: [
    { key: "remarks", label: "Remarks, if any", type: "textarea" },
    { key: "sap_document_number", label: "SAP Document Number", type: "text" },
    { key: "posting_date", label: "Posting Date", type: "date" },
    { key: "payment_bank_documents", label: "Payment Bank Documents", type: "file" },
    { key: "sap_username", label: "SAP Username", type: "text" },
  ],
  close_request: [{ key: "closing_remarks", label: "Remarks, if any", type: "textarea" }],
  approved: [{ key: "approval_remarks", label: "Approval Remarks", type: "textarea" }],
};

export const ALL_SECTION_FIELDS = {
  master: MASTER_FIELDS,
  ...STAGE_FIELD_CONFIG,
};
