# Generated by Django 6.0.5 on 2026-06-03 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndemnityTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('financial_year', models.CharField(max_length=20)),
                ('assessment_year', models.CharField(max_length=20)),
                ('date_of_notice_order', models.DateField()),
                ('date_of_filing_appeal_writ', models.DateField(blank=True, null=True)),
                ('date_of_communication_sent_to_essar', models.DateField(blank=True, null=True)),
                ('disputed_tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('interest', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('penalty', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_demand_as_per_order', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('estimated_interest', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('estimated_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_liability', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('possible_amount_of_claim', models.BooleanField(default=False)),
                ('covered_under_specific_indemnity', models.BooleanField(default=False)),
                ('appearing_in_disclosure_letter', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='indemnity/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('entity_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.legalentity')),
                ('issue_involved', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.issue')),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_last_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'indemnity_tracker',
            },
        ),
    ]
