# Generated by Django 5.2.14 on 2026-06-11 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indemnity', '0001_initial'),
        ('masters', '0005_bank_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indemnitytracker',
            name='appearing_in_disclosure_letter',
            field=models.BooleanField(default=False, verbose_name='Whether appearing in disclosure letter?'),
        ),
        migrations.AlterField(
            model_name='indemnitytracker',
            name='assessment_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.assessmentyear'),
        ),
        migrations.AlterField(
            model_name='indemnitytracker',
            name='covered_under_specific_indemnity',
            field=models.BooleanField(default=False, verbose_name='Whether covered under specific indemnity?'),
        ),
        migrations.AlterField(
            model_name='indemnitytracker',
            name='disputed_tax_amount',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='indemnitytracker',
            name='entity_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.entityname'),
        ),
        migrations.AlterField(
            model_name='indemnitytracker',
            name='estimated_interest',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='indemnitytracker',
            name='estimated_penalty',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='indemnitytracker',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.financialyear'),
        ),
        migrations.AlterField(
            model_name='indemnitytracker',
            name='interest',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='indemnitytracker',
            name='issue_involved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.issue'),
        ),
        migrations.AlterField(
            model_name='indemnitytracker',
            name='penalty',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='indemnitytracker',
            name='possible_amount_of_claim',
            field=models.BooleanField(default=False, verbose_name='Possible amount of claim > INR 40 crores?'),
        ),
        migrations.AlterField(
            model_name='indemnitytracker',
            name='total_demand_as_per_order',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='indemnitytracker',
            name='total_liability',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
