"""Workflow stage names and editable field mapping for TDS Opinion."""

WORKFLOW_STAGE_NAMES = [
    "Initiated",
    "TDS Opinion",
    "Invoice Posting",
    "Bank Detail",
    "Form 146 Request",
    "Form 145 Request",
    "Payment Details",
    "Close Request",
    "Approved",
]

MASTER_INITIATED_FIELDS = [
    "remarks",
    "company",
    "vendor",
    "pan_number",
    "tin_number",
    "po_npo",
    "grossing_up",
    "currency",
    "particular",
    "invoice_number",
    "opinion_invoice_amount",
    "invoice_date",
    "invoice_file",
    "form_10f_file",
    "form_10f_valid_upto",
    "trc_file",
    "trc_valid_upto",
    "contract_agreement_copy",
    "agreement_valid_upto",
    "pan_file",
    "pan_valid_upto",
    "no_pe_declaration_file",
    "no_pe_valid_upto",
    "proof_of_reimbursement_file",
    "reimbursement_valid_upto",
]

STAGE_SECTION_KEYS = {
    "Initiated": "master",
    "TDS Opinion": "tds_opinion_stage",
    "Invoice Posting": "invoice_posting",
    "Bank Detail": "bank_detail",
    "Form 146 Request": "form_146",
    "Form 145 Request": "form_145",
    "Payment Details": "payment_detail",
    "Close Request": "close_request",
    "Approved": "approved",
}

ACCORDION_SECTIONS = [
    {"stage": "Close Request", "key": "close_request", "title": "Close Request"},
    {"stage": "Payment Details", "key": "payment_detail", "title": "Payment Details"},
    {"stage": "Form 145 Request", "key": "form_145", "title": "145 Form Request"},
    {"stage": "Form 146 Request", "key": "form_146", "title": "146 Form Request"},
    {"stage": "Bank Detail", "key": "bank_detail", "title": "Bank Details"},
    {"stage": "Invoice Posting", "key": "invoice_posting", "title": "Invoice Posting"},
    {"stage": "TDS Opinion", "key": "tds_opinion_stage", "title": "TDS Opinion"},
    {"stage": "Initiated", "key": "master", "title": "Opinion request"},
]

STAGE_MODEL_FIELDS = {
    "tds_opinion_stage": [
        "country",
        "vendor_status",
        "has_trc",
        "has_no_pe",
        "has_e_form_10f",
        "it_or_dtaa",
        "grossing_up_applicable",
        "nature_of_service",
        "invoice_value_fc",
        "taxable_in_india",
        "assesseable_value_fc",
        "exchange_rate_date",
        "exchange_rate",
        "invoice_value_inr",
        "assesseable_value_inr",
        "tds_section",
        "tax_rate",
        "ldc_certificate",
        "form_146_type",
        "tds_amount_fc",
        "tds_amount_inr",
        "net_payable_fc",
        "net_payable_inr",
        "income_amount",
        "external_document",
        "opinion_remarks",
    ],
    "invoice_posting": [
        "posting_remarks",
        "document_number",
        "invoice_posting_date",
        "description",
    ],
    "bank_detail": [
        "bank_remarks",
        "bank_ifsc_code",
        "bank_name",
        "branch_name",
        "bsr_code",
        "proposed_remittance_date",
        "rbi_purpose_code",
        "rbi_sub_code",
        "form_146_type",
        "external_ca",
        "multiple_15ca_cb",
        "generate_single_15ca_cb",
        "itdrein",
    ],
    "form_146": [
        "remarks",
        "form_146_attachment",
        "comparison_status",
        "ack_number",
        "ack_date",
        "udin",
        "sap_document_number",
        "invoice_posting_date",
    ],
    "form_145": [
        "remarks",
        "ack_number",
        "posting_date",
        "bot_status",
        "form_ca_file",
    ],
    "payment_detail": [
        "remarks",
        "sap_document_number",
        "posting_date",
        "payment_bank_documents",
        "sap_username",
    ],
    "close_request": ["closing_remarks"],
    "approved": ["approval_remarks"],
}

STAGE_FILE_FIELDS = {
    "master": [
        "invoice_file",
        "form_10f_file",
        "trc_file",
        "contract_agreement_copy",
        "pan_file",
        "no_pe_declaration_file",
        "proof_of_reimbursement_file",
    ],
    "tds_opinion_stage": ["external_document"],
    "form_146": ["form_146_attachment"],
    "form_145": ["form_ca_file"],
    "payment_detail": ["payment_bank_documents"],
}
