# Generated by Django 5.2.14 on 2026-06-08 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_legalentity_certificate_of_incorporation_and_more'),
        ('tax_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdsopinion',
            name='agreement_valid_upto',
            field=models.DateField(blank=True, null=True, verbose_name='Valid Upto'),
        ),
        migrations.AddField(
            model_name='tdsopinion',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tds_company', to='masters.legalentity'),
        ),
        migrations.AddField(
            model_name='tdsopinion',
            name='contract_agreement_copy',
            field=models.FileField(blank=True, null=True, upload_to='tds_opinion/agreement/', verbose_name='Contract/ Agreement Copy'),
        ),
        migrations.AddField(
            model_name='tdsopinion',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.currency'),
        ),
        migrations.AddField(
            model_name='tdsopinion',
            name='form_10f_file',
            field=models.FileField(blank=True, null=True, upload_to='tds_opinion/form10f/', verbose_name='Electronically filed form 10F'),
        ),
        migrations.AddField(
            model_name='tdsopinion',
            name='form_10f_valid_upto',
            field=models.DateField(blank=True, null=True, verbose_name='Valid Upto'),
        ),
        migrations.AddField(
            model_name='tdsopinion',
            name='grossing_up',
            field=models.BooleanField(default=False, verbose_name='Grossing up'),
        ),
        migrations.AddField(
            model_name='tdsopinion',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='tds_opinion/invoice/', verbose_name='Invoice File'),
        ),
        migrations.AddField(
            model_name='tdsopinion',
            name='no_pe_declaration_file',
            field=models.FileField(blank=True, null=True, upload_to='tds_opinion/no_pe/', verbose_name='No Permanent (NO PE) Establishment Declaration/ Tax Residency Declaration'),
        ),
        migrations.AddField(
            model_name='tdsopinion',
            name='no_pe_valid_upto',
            field=models.DateField(blank=True, null=True, verbose_name='Valid Upto'),
        ),
        migrations.AddField(
            model_name='tdsopinion',
            name='open_with',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tdsopinion',
            name='opinion_invoice_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Opinion/Invoice Amount'),
        ),
        migrations.AddField(
            model_name='tdsopinion',
            name='pan_file',
            field=models.FileField(blank=True, null=True, upload_to='tds_opinion/pan/', verbose_name='PAN'),
        ),
        migrations.AddField(
            model_name='tdsopinion',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PAN Number'),
        ),
        migrations.AddField(
            model_name='tdsopinion',
            name='pan_valid_upto',
            field=models.DateField(blank=True, null=True, verbose_name='Valid Upto'),
        ),
        migrations.AddField(
            model_name='tdsopinion',
            name='particular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.particular'),
        ),
        migrations.AddField(
            model_name='tdsopinion',
            name='po_npo',
            field=models.BooleanField(default=False, verbose_name='PO / NPO'),
        ),
        migrations.AddField(
            model_name='tdsopinion',
            name='proof_of_reimbursement_file',
            field=models.FileField(blank=True, null=True, upload_to='tds_opinion/reimbursement/', verbose_name='Proof of reimbursement claims'),
        ),
        migrations.AddField(
            model_name='tdsopinion',
            name='reimbursement_valid_upto',
            field=models.DateField(blank=True, null=True, verbose_name='Valid Upto'),
        ),
        migrations.AddField(
            model_name='tdsopinion',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks, if any'),
        ),
        migrations.AddField(
            model_name='tdsopinion',
            name='revert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tdsopinion',
            name='tin_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TIN Number'),
        ),
        migrations.AddField(
            model_name='tdsopinion',
            name='trc_file',
            field=models.FileField(blank=True, null=True, upload_to='tds_opinion/trc/', verbose_name='Tax Residency Certificate (TRC)'),
        ),
        migrations.AddField(
            model_name='tdsopinion',
            name='trc_valid_upto',
            field=models.DateField(blank=True, null=True, verbose_name='Valid Upto'),
        ),
        migrations.AddField(
            model_name='tdsopinion',
            name='vendor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tdsopinion',
            name='company_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tdsopinion',
            name='invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='Invoice Date'),
        ),
        migrations.AlterField(
            model_name='tdsopinion',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Invoice Number'),
        ),
        migrations.AlterField(
            model_name='tdsopinion',
            name='request_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tdsopinion',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tdsopinion',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
