# Generated by Django 5.2.14 on 2026-06-09 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_requests', '0002_tdsopinion_agreement_valid_upto_tdsopinion_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_remarks', models.TextField(blank=True, null=True, verbose_name='Approval Remarks')),
                ('tds_opinion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approved_stage', to='tax_requests.tdsopinion')),
            ],
            options={
                'db_table': 'approved_stage',
            },
        ),
        migrations.CreateModel(
            name='BankDetailStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Name')),
                ('account_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Account Number')),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='IFSC Code')),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Branch Name')),
                ('beneficiary_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Beneficiary Name')),
                ('tds_opinion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_detail', to='tax_requests.tdsopinion')),
            ],
            options={
                'db_table': 'bank_detail_stage',
            },
        ),
        migrations.CreateModel(
            name='CloseRequestStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_remarks', models.TextField(blank=True, null=True, verbose_name='Closing Remarks')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Request Closed')),
                ('tds_opinion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='close_request', to='tax_requests.tdsopinion')),
            ],
            options={
                'db_table': 'close_request_stage',
            },
        ),
        migrations.CreateModel(
            name='Form145Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ack_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Form 145 Acknowledgement Number')),
                ('request_date', models.DateField(blank=True, null=True, verbose_name='Request Date')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tds_opinion/form145/', verbose_name='Form 145 Attachment')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('tds_opinion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form_145', to='tax_requests.tdsopinion')),
            ],
            options={
                'db_table': 'form_145_stage',
            },
        ),
        migrations.CreateModel(
            name='Form146Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ack_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Form 146 Acknowledgement Number')),
                ('request_date', models.DateField(blank=True, null=True, verbose_name='Request Date')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tds_opinion/form146/', verbose_name='Form 146 Attachment')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('tds_opinion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form_146', to='tax_requests.tdsopinion')),
            ],
            options={
                'db_table': 'form_146_stage',
            },
        ),
        migrations.CreateModel(
            name='InvoicePostingStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_document_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='SAP Document Number')),
                ('posting_date', models.DateField(blank=True, null=True, verbose_name='Posting Date')),
                ('posting_remarks', models.TextField(blank=True, null=True, verbose_name='Posting Remarks')),
                ('tds_opinion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_posting', to='tax_requests.tdsopinion')),
            ],
            options={
                'db_table': 'invoice_posting_stage',
            },
        ),
        migrations.CreateModel(
            name='PaymentDetailStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_document_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment Document Number')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Payment Date')),
                ('net_amount_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Net Amount (INR)')),
                ('payment_remarks', models.TextField(blank=True, null=True, verbose_name='Payment Remarks')),
                ('tds_opinion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_detail', to='tax_requests.tdsopinion')),
            ],
            options={
                'db_table': 'payment_detail_stage',
            },
        ),
        migrations.CreateModel(
            name='TDSOpinionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tax Rate (%)')),
                ('tds_section', models.CharField(blank=True, max_length=50, null=True, verbose_name='TDS Section')),
                ('opinion_remarks', models.TextField(blank=True, null=True, verbose_name='Opinion Remarks')),
                ('recommended_action', models.CharField(blank=True, max_length=255, null=True, verbose_name='Recommended Action')),
                ('tds_opinion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tds_opinion_stage', to='tax_requests.tdsopinion')),
            ],
            options={
                'db_table': 'tds_opinion_stage',
            },
        ),
    ]
