# Generated by Django 5.2.14 on 2026-06-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_requests', '0003_approvedstage_bankdetailstage_closerequeststage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetailstage',
            name='account_no',
        ),
        migrations.RemoveField(
            model_name='bankdetailstage',
            name='beneficiary_name',
        ),
        migrations.RemoveField(
            model_name='bankdetailstage',
            name='ifsc_code',
        ),
        migrations.RemoveField(
            model_name='closerequeststage',
            name='is_closed',
        ),
        migrations.RemoveField(
            model_name='form145stage',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='form145stage',
            name='request_date',
        ),
        migrations.RemoveField(
            model_name='form146stage',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='form146stage',
            name='request_date',
        ),
        migrations.RemoveField(
            model_name='invoicepostingstage',
            name='posting_date',
        ),
        migrations.RemoveField(
            model_name='invoicepostingstage',
            name='sap_document_no',
        ),
        migrations.RemoveField(
            model_name='paymentdetailstage',
            name='net_amount_inr',
        ),
        migrations.RemoveField(
            model_name='paymentdetailstage',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='paymentdetailstage',
            name='payment_document_number',
        ),
        migrations.RemoveField(
            model_name='paymentdetailstage',
            name='payment_remarks',
        ),
        migrations.RemoveField(
            model_name='tdsopinionstage',
            name='recommended_action',
        ),
        migrations.AddField(
            model_name='bankdetailstage',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Bank IFSC Code'),
        ),
        migrations.AddField(
            model_name='bankdetailstage',
            name='bank_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks, if any'),
        ),
        migrations.AddField(
            model_name='bankdetailstage',
            name='bsr_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='BSR Code'),
        ),
        migrations.AddField(
            model_name='bankdetailstage',
            name='external_ca',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='External CA'),
        ),
        migrations.AddField(
            model_name='bankdetailstage',
            name='form_146_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Form 146 - Type'),
        ),
        migrations.AddField(
            model_name='bankdetailstage',
            name='generate_single_15ca_cb',
            field=models.BooleanField(default=False, verbose_name='Generate single 15CA/CB against multiple request'),
        ),
        migrations.AddField(
            model_name='bankdetailstage',
            name='itdrein',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ITDREIN'),
        ),
        migrations.AddField(
            model_name='bankdetailstage',
            name='multiple_15ca_cb',
            field=models.BooleanField(default=False, verbose_name='Multiple 15CA/CB'),
        ),
        migrations.AddField(
            model_name='bankdetailstage',
            name='proposed_remittance_date',
            field=models.DateField(blank=True, null=True, verbose_name='Proposed date of remittance'),
        ),
        migrations.AddField(
            model_name='bankdetailstage',
            name='rbi_purpose_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='RBI Purpose Code'),
        ),
        migrations.AddField(
            model_name='bankdetailstage',
            name='rbi_sub_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='RBI Sub Code'),
        ),
        migrations.AddField(
            model_name='form145stage',
            name='bot_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bot Status'),
        ),
        migrations.AddField(
            model_name='form145stage',
            name='form_ca_file',
            field=models.FileField(blank=True, null=True, upload_to='tds_opinion/form145/', verbose_name='Form CA file'),
        ),
        migrations.AddField(
            model_name='form145stage',
            name='posting_date',
            field=models.DateField(blank=True, null=True, verbose_name='Posting Date'),
        ),
        migrations.AddField(
            model_name='form146stage',
            name='ack_date',
            field=models.DateField(blank=True, null=True, verbose_name='Acknowledgement Date'),
        ),
        migrations.AddField(
            model_name='form146stage',
            name='comparison_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Form 146 Comparison Status'),
        ),
        migrations.AddField(
            model_name='form146stage',
            name='form_146_attachment',
            field=models.FileField(blank=True, null=True, upload_to='tds_opinion/form146/', verbose_name='Form 146'),
        ),
        migrations.AddField(
            model_name='form146stage',
            name='invoice_posting_date',
            field=models.DateField(blank=True, null=True, verbose_name='Invoice Posting Date'),
        ),
        migrations.AddField(
            model_name='form146stage',
            name='sap_document_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SAP Document Number'),
        ),
        migrations.AddField(
            model_name='form146stage',
            name='udin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='UDIN'),
        ),
        migrations.AddField(
            model_name='invoicepostingstage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='invoicepostingstage',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Document Number'),
        ),
        migrations.AddField(
            model_name='invoicepostingstage',
            name='invoice_posting_date',
            field=models.DateField(blank=True, null=True, verbose_name='Invoice Posting Date'),
        ),
        migrations.AddField(
            model_name='paymentdetailstage',
            name='payment_bank_documents',
            field=models.FileField(blank=True, null=True, upload_to='tds_opinion/payment/', verbose_name='Payment Bank Documents'),
        ),
        migrations.AddField(
            model_name='paymentdetailstage',
            name='posting_date',
            field=models.DateField(blank=True, null=True, verbose_name='Posting Date'),
        ),
        migrations.AddField(
            model_name='paymentdetailstage',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks, if any'),
        ),
        migrations.AddField(
            model_name='paymentdetailstage',
            name='sap_document_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SAP Document Number'),
        ),
        migrations.AddField(
            model_name='paymentdetailstage',
            name='sap_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SAP Username'),
        ),
        migrations.AddField(
            model_name='tdsopinionstage',
            name='assesseable_value_fc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='tdsopinionstage',
            name='assesseable_value_inr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='tdsopinionstage',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tdsopinionstage',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tdsopinionstage',
            name='exchange_rate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tdsopinionstage',
            name='external_document',
            field=models.FileField(blank=True, null=True, upload_to='tds_opinion/external/'),
        ),
        migrations.AddField(
            model_name='tdsopinionstage',
            name='form_146_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Form 146 - Type'),
        ),
        migrations.AddField(
            model_name='tdsopinionstage',
            name='grossing_up_applicable',
            field=models.BooleanField(default=False, verbose_name='Grossing up or not'),
        ),
        migrations.AddField(
            model_name='tdsopinionstage',
            name='has_e_form_10f',
            field=models.BooleanField(default=False, verbose_name='E form 10F'),
        ),
        migrations.AddField(
            model_name='tdsopinionstage',
            name='has_no_pe',
            field=models.BooleanField(default=False, verbose_name='No PE Declaration'),
        ),
        migrations.AddField(
            model_name='tdsopinionstage',
            name='has_trc',
            field=models.BooleanField(default=False, verbose_name='Tax Residency Certificate (TRC)'),
        ),
        migrations.AddField(
            model_name='tdsopinionstage',
            name='income_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Amount of income'),
        ),
        migrations.AddField(
            model_name='tdsopinionstage',
            name='invoice_value_fc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='tdsopinionstage',
            name='invoice_value_inr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='tdsopinionstage',
            name='it_or_dtaa',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='As per IT or DTAA'),
        ),
        migrations.AddField(
            model_name='tdsopinionstage',
            name='ldc_certificate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tdsopinionstage',
            name='nature_of_service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tdsopinionstage',
            name='net_payable_fc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='tdsopinionstage',
            name='net_payable_inr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='tdsopinionstage',
            name='taxable_in_india',
            field=models.BooleanField(default=True, verbose_name='Whether Taxable in INDIA'),
        ),
        migrations.AddField(
            model_name='tdsopinionstage',
            name='tds_amount_fc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='tdsopinionstage',
            name='tds_amount_inr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='tdsopinionstage',
            name='vendor_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status of Vendor'),
        ),
        migrations.AlterField(
            model_name='bankdetailstage',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Bank'),
        ),
        migrations.AlterField(
            model_name='bankdetailstage',
            name='branch_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Branch of the Bank'),
        ),
        migrations.AlterField(
            model_name='closerequeststage',
            name='closing_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks, if any'),
        ),
        migrations.AlterField(
            model_name='form145stage',
            name='ack_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Acknowledgement Number'),
        ),
        migrations.AlterField(
            model_name='form145stage',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks, if any'),
        ),
        migrations.AlterField(
            model_name='form146stage',
            name='ack_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Acknowledgement Number'),
        ),
        migrations.AlterField(
            model_name='form146stage',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks, if any'),
        ),
        migrations.AlterField(
            model_name='invoicepostingstage',
            name='posting_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks, if any'),
        ),
        migrations.AlterField(
            model_name='tdsopinionstage',
            name='opinion_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks, if any'),
        ),
        migrations.AlterField(
            model_name='tdsopinionstage',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='TDS Rate (%)'),
        ),
    ]
