# Generated by Django 5.2.14 on 2026-06-16 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0015_vendorstatus'),
        ('tax_requests', '0004_remove_bankdetailstage_account_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdsopinionstage',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.currency'),
        ),
        migrations.AlterField(
            model_name='tdsopinionstage',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.country'),
        ),
        migrations.AlterField(
            model_name='tdsopinionstage',
            name='form_146_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.type15cb'),
        ),
        migrations.AlterField(
            model_name='tdsopinionstage',
            name='nature_of_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.natureofservice'),
        ),
        migrations.AlterField(
            model_name='tdsopinionstage',
            name='vendor_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.vendorstatus'),
        ),
    ]
