# Generated by Django 5.2.14 on 2026-06-16 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0015_vendorstatus'),
        ('tax_requests', '0005_tdsopinionstage_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetailstage',
            name='form_146_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.type15cb', verbose_name='Form 146 - Type'),
        ),
    ]
