# Generated by Django 5.2.14 on 2026-06-16 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0015_vendorstatus'),
        ('tax_requests', '0006_alter_bankdetailstage_form_146_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetailstage',
            name='bank_ifsc_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.bank', verbose_name='Bank IFSC Code'),
        ),
        migrations.AlterField(
            model_name='bankdetailstage',
            name='external_ca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.externalca', verbose_name='External CA'),
        ),
        migrations.AlterField(
            model_name='bankdetailstage',
            name='rbi_purpose_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.rbipurposecode', verbose_name='RBI Purpose Code'),
        ),
        migrations.AlterField(
            model_name='bankdetailstage',
            name='rbi_sub_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.rbipurposesubcode', verbose_name='RBI Sub Code'),
        ),
    ]
