# Generated by Django 5.2.14 on 2026-06-17 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax_requests', '0007_alter_bankdetailstage_bank_ifsc_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form146stage',
            name='invoice_posting_date',
        ),
        migrations.RemoveField(
            model_name='form146stage',
            name='sap_document_number',
        ),
    ]
