# Generated by Django 5.2.14 on 2026-06-18 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0016_purchaseorder'),
        ('tax_requests', '0008_remove_form146stage_invoice_posting_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdsopinion',
            name='po_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.purchaseorder'),
        ),
    ]
