# Generated by Django 5.2.14 on 2026-06-30 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0016_purchaseorder'),
        ('tax_requests', '0009_tdsopinion_po_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdsopinionstage',
            name='ldc_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.ldccertificate'),
        ),
    ]
