# Generated by Django 5.2.14 on 2026-07-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_requests', '0010_alter_tdsopinionstage_ldc_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='form146stage',
            name='download_form_146',
            field=models.FileField(blank=True, null=True, upload_to='tds_opinion/generated_form146/', verbose_name='Download Form 146'),
        ),
        migrations.AddField(
            model_name='form146stage',
            name='download_form_146_comparison',
            field=models.FileField(blank=True, null=True, upload_to='tds_opinion/form146_comparison/', verbose_name='Download Form 146 Comparison'),
        ),
    ]
