# Generated by Django 5.2.14 on 2026-07-02 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax_requests', '0011_form146stage_download_form_146_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form145stage',
            old_name='form_ca_file',
            new_name='form_145_file',
        ),
    ]
