# Generated by Django 5.2.14 on 2026-07-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_requests', '0012_rename_form_ca_file_form145stage_form_145_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form145stage',
            name='form_145_file',
            field=models.FileField(blank=True, null=True, upload_to='tds_opinion/form145/', verbose_name='Form 145 file'),
        ),
    ]
