# Generated by Django 5.2.14 on 2026-07-06 09:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0016_purchaseorder'),
        ('tax_requests', '0013_alter_form145stage_form_145_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Approval Token')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Is Valid')),
                ('is_approved', models.BooleanField(blank=True, null=True, verbose_name='Approved')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('external_ca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.externalca', verbose_name='External CA')),
                ('tds_opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_links', to='tax_requests.tdsopinion')),
            ],
            options={
                'db_table': 'approval_link',
            },
        ),
    ]
