# Generated by Django 5.2.14 on 2026-07-09 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0016_purchaseorder'),
        ('tax_requests', '0014_approvallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdsopinionstage',
            name='tds_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.tdssection', verbose_name='TDS Section'),
        ),
    ]
