# Generated by Django 5.2.14 on 2026-06-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_issue_issue_title_issue_issue_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='issue_name',
        )
    ]
