# Generated by Django 5.2.14 on 2026-06-11 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_bank_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='branch_address',
            new_name='address',
        ),
    ]
