# Generated by Django 5.2.14 on 2026-06-11 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_rename_branch_address_bank_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('value_date', models.DateField()),
                ('ttbuy', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.currency')),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_last_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'currency_rate',
            },
        ),
        migrations.CreateModel(
            name='ExternalCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('firm_name', models.CharField(max_length=255)),
                ('firm_registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('partner_name', models.CharField(max_length=255)),
                ('membership_number', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email_id', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_last_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'external_ca',
            },
        ),
    ]
