# Generated by Django 5.2.14 on 2026-06-11 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_currencyrate_externalca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalca',
            old_name='partner_name',
            new_name='full_name_of_the_partner',
        ),
    ]
