# Generated by Django 5.2.14 on 2026-06-11 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_tdsrate_tdssection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tdssection',
            old_name='description',
            new_name='TDS_section',
        ),
    ]
