# Generated by Django 5.2.14 on 2026-06-12 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_rename_description_tdssection_tds_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NatureOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('service_description', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_last_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nature_of_service',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('vendor_code', models.CharField(max_length=200, unique=True)),
                ('vendor_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('addr_no', models.CharField(blank=True, max_length=10, null=True)),
                ('house_no', models.CharField(blank=True, max_length=10, null=True)),
                ('street2', models.CharField(blank=True, max_length=40, null=True)),
                ('street3', models.CharField(blank=True, max_length=40, null=True)),
                ('street4', models.CharField(blank=True, max_length=40, null=True)),
                ('street5', models.CharField(blank=True, max_length=40, null=True)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('pin_code', models.CharField(blank=True, max_length=15, null=True)),
                ('tin', models.CharField(blank=True, max_length=50, null=True)),
                ('pan_if_any', models.CharField(blank=True, max_length=50, null=True)),
                ('exemption_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('certificate_number', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.country')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_last_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
        migrations.CreateModel(
            name='LDACCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('certificate_number', models.CharField(max_length=100)),
                ('under_section_obtained', models.CharField(max_length=100)),
                ('issued_officer', models.CharField(max_length=255)),
                ('officer_designation', models.CharField(max_length=255)),
                ('certificate_date', models.DateField()),
                ('certificate_valid_from', models.DateField()),
                ('certificate_valid_to', models.DateField()),
                ('certificate_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ldc_certificates', to='masters.legalentity')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ldc_certificates', to='masters.supplier')),
            ],
            options={
                'db_table': 'ldc_certificate',
            },
        ),
    ]
