# Generated by Django 5.2.14 on 2026-06-15 04:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0012_rbipurposecode_rbipurposesubcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LDACCertificate',
            new_name='LDCCertificate',
        ),
    ]
