from .vertical import Vertical
from .role import Role
from .law import Law
from .period import Period
from .amount import AmountUnit
from .forum import Forum
from .issue import Issue
from .exchange_rate import ExchangeRate
from .document_master import DocumentMaster
from .form_master import FormMaster
from .law_rule import LawRule

from .legal_entity import LegalEntity
from .law_section import LawSection
from .consultant import Consultant
from .user_master import UserMaster
from .compliance import Compliance
from .director import Director
from .intragroup_agreement import IntragroupAgreement
from .tp_benchmarking import TPBenchmarking
from .tp_study_report import TPStudyReport
from .it_act_mapping import ITActMapping
from .material_hsn import MaterialHSN
from .assessment_year import AssessmentYear
from .financial_year import FinancialYear
from .entity_name import EntityName
from .currency import Currency
from .particular import Particular